### ISSUE TITLE
Theme Picker UI Change

### ISSUE THREAD

**Issue by kiichi** [nitink-prog/LIU-Printers-Database#1]
## Description

The stakeholder wants to reduce the blank space on top of the printer list so that we can utilize the main page for small screen.

## Specifications

1. Create a panel that contains current color scheme
2. Create a Toggle button with an icon
3. Default state is closed so that you can save the space on top
4. When the user clicks, it opens up the panel
5. When the user select the theme, the panel should be collapsed.

## Screenshots

![React_App](https://user-images.githubusercontent.com/396816/164089965-dd5bc99f-2f81-42a4-9fc4-27fcbd36ea3b.jpg)

## Test Steps

1. Make sure the panel is collapsed when the user landed on this page
2. When the user clicks on the toggle icon, the panel should be opening
3. When the user clicks on the toggle button gain, the panel should be closed
4. Theme picker should work same as before

**Comment by nitink-prog** [comment]
I've made some changes in the feature/theme-picker branch.
1. Moved <ThemeSelector> into the <Navbar>
2. Added a "display settings" icon to toggle <ThemeSelector>
3. Adjusted CSS for styling parity.

Take a look and let me know if satisfactory.

**Comment by kiichi** [comment]
@nitink-prog looks great, and I see the vertical alignment + margin were adjusted. How about we define the boundary for the theme picker box? I just thought about this kind drawer panel design. The point is when it's expand, the user can not distinguish the component which is blended into the navbar.
![React_App](https://user-images.githubusercontent.com/396816/164303009-e53fde81-04cc-44fb-aa80-1494e8bbd7dc.jpg)
